apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp3
spec:
  replicas: 3
  selector:
    matchLabels:
      whatsapp: image
  template:
    metadata:
      name: whatsapp-pod3
      labels:
        whatsapp: image
    spec:
      containers:
      - name: whatsapp-con3
        image: faizshahnawaz99/whatsapp2:v1
        ports:
        - containerPort: 80

